### ISSUE TITLE
doesn't seem to be working ?

### ISSUE THREAD

**Issue by mellery451** [marxin/neo-rtags#1]
I'm using lazy.nvim for plugins and this plugin doesn't seem to register its maps and there are no global callable functions matching NeoRtags* ... is there something else I need to do to enable this plugin? Any other tips on debugging the issue? 

Version info:

```
- OK nvim: NVIM v0.10.1
  Build type: Release
  LuaJIT 2.1.1724232689
```

and pynvim is there:

```
provider.python: require("provider.python.health").check()

Python 3 provider (optional) ~
- `g:python3_host_prog` is not set. Searching for python3 in the environment.
- Executable: /home/linuxbrew/.linuxbrew/bin/python3
- Python version: 3.12.5
- pynvim version: 0.5.0
- OK Latest pynvim is installed.
```

**Comment by marxin** [comment]
I'm sorry, but this project is already archived. I would recommend switching to `clangd` with YouCompleteMe: https://clangd.llvm.org/installation#youcompleteme.
